config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root "articles#index"  
  get "/fill-articles", to: "articles#fill"
  get "/search", to: "search#index", :as => 'search_page'

  resources :articles do
    resources :comments
    resources :likes
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    has_many :comments
    has_many :likes, dependent: :destroy

    validates :title, presence: true
    validates :body, presence: true, length: { minimum: 10 }

    def number_of_dislikes
        self.likes.where(is_dislike:true).count
    end

    def number_of_likes
        self.likes.where(is_dislike:false).count
    end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
  belongs_to :user

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :article
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :comments
  has_many :likes, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
require 'rss'
require 'open-uri'

class ArticlesController < ApplicationController
  def index
    @articles = Article.order(id: :desc)
  end

  def show
    @article = Article.find(params[:id])
  end

  def fill
    url = 'https://www.nasa.gov/rss/dyn/earth.rss'
    open(url) do |rss|
      feed = RSS::Parser.parse(rss)
      feed.items.each do |item|
        article = Article.where(title:item.title,body:item.description).first_or_create  
      end
    end
    redirect_to action: "index"
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
    def create
        @article = Article.find(params[:article_id])
        @comment = @article.comments.create(comment_params)
        @comment.user = current_user
        @comment.save
        redirect_to article_path(@article)
      end

    def destroy
        @article = Article.find(params[:article_id])
        @comment = @article.comments.find(params[:id])
        @comment.destroy
        redirect_to article_path(@article)
      end
    
      private
        def comment_params
          params.require(:comment).permit(:body)
        end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    before_action :find_article
    before_action :authenticate_user!
    def create
        if already_liked?
            flash[:notice] = "You can't like more than once"
        else
            @like = @article.likes.create(user_id: current_user.id)
            @like.is_dislike = params[:is_dislike]
            @like.save
        end
        redirect_to article_path(@article)
    end
    private
    def find_article
        @article = Article.find(params[:article_id])
    end

    def already_liked?
        Like.where(user_id: current_user.id, article_id:
        params[:article_id]).exists?
      end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    if params[:search].blank?  
      redirect_to(root_path, alert: "Empty field!") and return  
    else  
      @parameter = params[:search].downcase  
      @results = Article.all.where("lower(title) LIKE ?","%" + @parameter + "%")
    end 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/articles/_header.html.erb
<nav class="navbar navbar-dark bg-primary navbar-expand-lg">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Webintel</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <li>
        <% if current_user %>
        <%= link_to "Sign out", destroy_user_session_path,
        method: :delete,
        data: { confirm: "Are you sure?" }, :style=>'color:#FFFFFF;text-decoration:none', :class => "nav-link css_class" %>
        <% else %>
        <%= link_to 'Sign up', new_user_registration_path, :style=>'color:#FFFFFF;text-decoration:none', :class => "nav-link css_class" %>
        </li>
        <li>
        <%= link_to 'Sign in', new_user_session_path, :style=>'color:#FFFFFF;text-decoration:none', :class => "nav-link css_class" %>
        </li>
        <% end %>      
      </ul>
      <%= form_tag(search_page_path, :method => "get",   
        class: 'navbar-form navbar-left') do %>  
      <div class="input-group">  
        <%= search_field_tag :search, params[:search], placeholder: "Search article..", class: "form-control" %>  
        <div class="input-group-btn">  
          <%= button_tag "Search", :class => 'btn mx-2 btn-outline-light ',:name => nil%>  
        </div>  
      </div>  
    <% end %>

    </div>
  </div>
</nav>

app/views/articles/index.html.erb
<%= form_with url: "/fill-articles", method: :get do |form| %>
  <button type="submit" class="btn my-3 btn-primary">Read and store the feed</button>
<% end %>


<h1>Articles</h1>


<ul>
  <% @articles.each do |article| %>
    <li>
      <a href="/articles/<%= article.id %>">
        <%= article.title %>
      </a>
    </li>
  <% end %>
</ul>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<span class="g-color-gray-dark-v4 g-font-size-12"><i><%= @article.created_at.to_s(:long) %></i></span>


<p><%= @article.body %></p>

<% if current_user %>
<% pre_like = @article.likes.find { |like| like.user_id == current_user.id} %>
<% if pre_like %>
    <% if pre_like.is_dislike %>
    <p><i>You have disliked this post</i></p>
    <% else %>
    <p><i>You have liked this post</i></p>
    <% end %>
<% else %>
  <%= button_to 'Like', article_likes_path(@article,is_dislike: 0), method: :post, :class => "btn m-1 btn-primary" %>
  <%= button_to 'Dislike', article_likes_path(@article,is_dislike: 1), method: :post, :class => "btn m-1 btn-danger" %>
  <% end %>
  <% end %>


<% if @article.number_of_likes > 0 %>
<h2><%= @article.number_of_likes %> like<%= @article.number_of_likes > 1 ? 's' : '' %> </h2>
<ul>
<% @article.likes.each do |like| %>
    <% if !like.is_dislike %>
        <li>
            <%= like.user.email %>
        </li>
    <% end %>
  <% end %>
</ul>
<% end %>

<% if @article.number_of_dislikes > 0 %>
<h2><%= @article.number_of_dislikes %> dislike<%= @article.number_of_dislikes > 1 ? 's' : '' %> </h2>
<ul>
<% @article.likes.each do |like| %>
    <% if like.is_dislike %>
        <li>
            <%= like.user.email %>
        </li>
    <% end %>
  <% end %>
</ul>
<% end %>



<% if @article.comments.count > 0 %>
<h2>Comments</h2>
<%= render @article.comments %>
<% end %>

<% if current_user %>
<h2>Add a comment:</h2>
<%= render 'comments/form' %>
<% end %>

app/views/comments/_comment.html.erb
<div class="card">
<div class="card-body">

<p>
  <h5 class="h5 g-color-gray-dark-v1 mb-0"><%= comment.user.email %></h5>
                <span class="g-color-gray-dark-v4 g-font-size-12"><i><%= comment.created_at.to_s(:long) %></i></span>
</p>

<p>
  <%= comment.body %>
</p>

<% if current_user == comment.user %>

<ul class="list-inline d-sm-flex my-0">
                <li class="list-inline-item ml-auto">
                  <a class="u-link-v5 g-color-gray-dark-v4 g-color-primary--hover" href="#!">
                    <i class="fa fa-reply g-pos-rel g-top-1 g-mr-3"></i>
                    <%= link_to 'Delete', [comment.article, comment],
                        method: :delete,
                        data: { confirm: "Are you sure?" } %>
                  </a>
                </li>
              </ul>
<% end %>
</div>
</div>

app/views/comments/_form.html.erb
<div class="">


<%= form_with model: [ @article, @article.comments.build ] do |form| %>
  <div class="field form-group">
  <p>
  <%= form.text_area :body, class:"form-control", placeholder:"Write comment.." %>

  </p>
  </div>
  

  <div class="actions">
    <%= form.submit "Send", class: 
    "btn btn-secondary" %>
  </div>

  <% end %>
</div>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">

    <title>Webintel</title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= render 'articles/header' %>
    <div class="container">
    
    <% if notice %>
    <%= render 'layouts/alerts' %>
  <% end %>

    <%= yield %>
    </div>
    
    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/search/index.html.erb
<h3>Search Result</h3>
    
<ul>
<% @results.each do |result| %>
  <li>
    <a href="/articles/<%= result.id %>">
      <%= result.title %>
    </a>
  </li>
<% end %>
</ul>